package br.com.leomotos.leomotos.servico.domain;

public enum TipoDeServico {
	REVISAO, TROCAR_OLEO, TROCAR_DISCO_DE_EMBRAGEM,
	FAZER_MOTOR, LUBRIFICAR_CABOS, APERTAR_CORRENTE,
	TROCAR_PNEUS, TROCAR_CAPA_DO_BANCO, TROCAR_RETENTOR,
	TROCAR_INGNIÇÃO, SERVICO_EM_GERAL;
}

